In [1]:
import numpy as np

# Define two 2x2 matrices
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

# Perform matrix multiplication
C = np.dot(A, B)

# Print the results
print("Matrix A:\n", A)
print("Matrix B:\n", B)
print("Matrix Multiplication (A x B):\n", C)

Matrix A:
 [[1 2]
 [3 4]]
Matrix B:
 [[5 6]
 [7 8]]
Matrix Multiplication (A x B):
 [[19 22]
 [43 50]]
